baseURL = "https://ericchi.moe/"
theme = "ericchi-blue"
identifier = "ericchi"
defaultContentLanguage = "en"
title = "Ericchi"
disableKinds = ["taxonomy", "taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  favicon = "/images/favicon.gif"
  friendsites = ""
  stuff = ""
  webrings = "<a href='https://itawebring.altervista.org/' target='_blank'><img src='/images/banners/webrings/italia.png' alt='Italian webring'></a> <a href='https://allyratworld.com/cafe/rose' target='_blank'><img src='/images/banners/webrings/caferose_88x31melo.png' alt='Café Rosé'></a> <a href='https://yume-ring.neocities.org/' target='_blank'><img src='/images/banners/webrings/yume-ring.png' alt='Yume-Ring'></a>"
  [socials]
    telegram = "https://t.me/EricchiYukia"
    youtube = "https://www.youtube.com/channel/UCG11xx7bQcbXB4ThsgsYs7w"
    github = "https://github.com/Ericchi"
    twitch = "https://twitch.tv/EricchiYukia"
    myanimelist = "https://myanimelist.net/profile/EricchiYukia"
    tumblr = "https://ericchiyukia.tumblr.com/"

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'en'
    weight = 1

  [languages.it]
    contentDir = 'content/it'
    languageName = 'it'
    weight = 2

[menu]
  [[languages.it.menu.main]]
    identifier = "posts"
    name = "Scarabocchi"
    url = "/posts"
    weight = 10

  [[languages.it.menu.main]]
    identifier = "toybox"
    name = "Giocattoli"
    url = "/games"
    weight = 20

  [[languages.it.menu.main]]
    identifier = "suggestions"
    name = "Segnalibri"
    url = "/suggestions"
    weight = 30

  [[languages.it.menu.main]]
    identifier = "about"
    name = "Ericchi"
    url = "/about"
    weight = 40

  [[languages.en.menu.main]]
    identifier = "posts"
    name = "Scribbles"
    url = "/posts"
    weight = 10

  [[languages.en.menu.main]]
    identifier = "toybox"
    name = "Toybox"
    url = "/games"
    weight = 20

  [[languages.en.menu.main]]
    identifier = "suggestions"
    name = "Bookmarks"
    url = "/suggestions"
    weight = 30

  [[languages.en.menu.main]]
    identifier = "about"
    name = "Ericchi"
    url = "/about"
    weight = 40
